name: Test the action

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          
        - name: macOS
          os: macos-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: geode-sdk/textureldr
          path: textureldr
    
      - uses: actions/checkout@v3
        with:
          path: myawesome

      - name: Build the mod
        uses: ./myawesome
        with:
          sdk: nightly
          build-config: RelWithDebInfo
          path: textureldr
          combine: true
      
  package:
    name: Package both builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: actions/checkout@v3
        with:
          path: myawesome

      - uses: ./myawesome/combine.yml
        id: build

      - uses: actions/upload-artifact@v3
        with:
          name: Build Output
          path: ${{ steps.build.outputs.output }}